### ISSUE TITLE
Authentication / Login

### ISSUE THREAD

**Issue by Latios96** [Latios96/cato#75]
Evaluate Keycloak: https://www.amazon.de/Keycloak-Management-Applications-protocols-applications/dp/1800562497/ref=sr_1_1_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=1ONZPT2W27QZQ&keywords=keycloak&qid=1644579605&sprefix=keycloak%2Caps%2C74&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyRDg4UVRZUkRYRURPJmVuY3J5cHRlZElkPUEwOTcwMTI5UDROODZEWVIxUDU5JmVuY3J5cHRlZEFkSWQ9QTA2NzgwNTUyTVMxNEFOUFhBOU01JndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

Evaluate: What about using an external OIDC Provider like Google (but with an Allow List?)

Evaluate: See https://github.com/authlib/demo-oauth-client

## Roadmap
- [x] User & UserReposititory implementieren
- [x]  Create User implementieren (cato_server_admin)
- [x] #81
- [x] install Keycloak / create Keycloak Docker Setup
- [x] #98
- [x] #82
- [x] whoami route implementieren
- [x] #117
- [x] User Informationen / Bereich im Frontend implementieren (oben Rechts in der Ecke reicht erstmal)
- [x] logout
- [x] #119
- [x] #101
- [x] #124
- [x] CRSF implementieren (Backend) https://github.com/frankie567/starlette-csrf
- [x] #118
- [x] #125
- [x] #126

Example Realm: 
[realm-export.zip](https://github.com/Latios96/cato/files/8161070/realm-export.zip)
