### ISSUE TITLE
Login & Authentifizierung implementieren (Backend)

### ISSUE THREAD

**Issue by Latios96** [Latios96/cato#82]
**Login:** 
- [x] redirect to Keycloak
- [x] read user information, create user if not existing yet, otherwise update if needed
- [x] create session
- [x] store session as http only cookie

**Implementation steps:** 
- [x] add OIDC config to AppConfiguration
- [x] implement creating or updating of user
- [x] add session middleware
- [x] implement LoginBlueprint
- [x] implement Login integration tests

**Usefull Links:**
https://github.com/authlib/demo-oauth-client
https://github.com/marcospereirampj/python-keycloak
